name: tripper

description: Tripper helps users to plan a new trip.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  http: ^0.13.4
  uuid: ^3.0.6
  localstore: ^1.2.3
  flutterfire_ui: ^0.4.2+3
  firebase_core: ^1.19.2
  cloud_firestore: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
